blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/qvcloud/broker/discussions
    about: Please confirm and discuss your ideas or questions before opening an issue.
